from sqlalchemy import Column, Integer, String, ForeignKey, create_engine
from sqlalchemy.orm import relationship, DeclarativeBase, Session

class Base(DeclarativeBase):
    pass    

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False)
    fullname = Column(String(100), optional=True)

    

engine = create_engine(
    "postgresql+psycopg2://postgres:k4sh%40L1014@localhost/userAccount", 
    echo=True #> True means it will log all the SQL statements generated by SQLAlchemy to the console. 
)
#  Table skeleton -> actual table convert / migration
Base.metadata.create_all(engine)
print("Tables created successfully.")


with Session(engine) as session:
    user1 = User(name="Alu Pidalu", fullname="")
    user2 = User(name="Jane", fullname="")
    session.add_all([user1, user2])
    session.commit()

    users = session.query(User).all()
    for user in users:
        print(user)




















        
# ORM program to database interaction using SQLAlchemy. It defines a User model, creates a PostgreSQL database connection, and performs basic CRUD operations.
# Pip means "Package Installer for Python". It is a tool used to install and manage software packages written in Python. It allows you to easily install, upgrade, and remove Python packages from the Python Package Index (PyPI) and other package repositories. You can use pip to install libraries and frameworks that are not included in the standard Python library, making it easier to develop and manage your Python projects.

# Create a table
#    create a class
# insert data into the table
#  update
#  delete
#  view/ select/ query data from the table

# mapped_column is a function used to store constraints on the column. It is used to specify the type of data that can be stored in the column, as well as any other constraints such as primary key, nullable, etc. 

# Optional: can be empty
